### ISSUE TITLE
New problem

### ISSUE THREAD

**Issue by kenny-opennix** [nschloe/launchpadtools#9] opened 2016-06-15 19:29 UTC
Hi,today i try again and get error. 

```
ymedvedev@fr01:~/launchpadtools$ launchpad-submit \
>   --dsc "http://http.debian.net/debian/pool/main/n/nginx/nginx_1.10.1-1.dsc" \
>   --ubuntu-releases trusty wily xenial yakkety  \
>   --ppa ymedvedev/backport   --update-patches
dget: retrieving http://http.debian.net/debian/pool/main/n/nginx/nginx_1.10.1-1.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3511  100  3511    0     0  10396      0 --:--:-- --:--:-- --:--:-- 10396
dget: retrieving http://http.debian.net/debian/pool/main/n/nginx/nginx_1.10.1.orig.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  887k  100  887k    0     0   764k      0  0:00:01  0:00:01 --:--:-- 2503k
dget: retrieving http://http.debian.net/debian/pool/main/n/nginx/nginx_1.10.1-1.debian.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  639k  100  639k    0     0   601k      0  0:00:01  0:00:01 --:--:-- 1081k
nginx_1.10.1-1.dsc:
      Good signature found
   validating nginx_1.10.1.orig.tar.gz
   validating nginx_1.10.1-1.debian.tar.xz
All files validated successfully.
dpkg-source: info: extracting nginx in nginx-1.10.1
dpkg-source: info: unpacking nginx_1.10.1.orig.tar.gz
dpkg-source: info: unpacking nginx_1.10.1-1.debian.tar.xz
dpkg-source: info: applying perl-use-dpkg-buildflags.patch
dpkg-source: info: applying 0002-Make-sure-signature-stays-the-same-in-all-nginx-buil.patch
Traceback (most recent call last):
  File "/usr/local/bin/launchpad-submit", line 99, in <module>
    args.debuild_params
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 209, in submit_dsc
    orig_tarball, debian_dir = _get_items_from_dsc(dsc)
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 460, in _get_items_from_dsc
    tar = tarfile.open(debian)
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

Your example give me error too

```
ymedvedev@fr01:~/launchpadtools$ launchpad-submit \
>   --dsc "http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.dsc" \
>   --ubuntu-releases trusty wily xenial yakkety  \
>   --ppa ymedvedev/backport
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2212  100  2212    0     0   2736      0 --:--:-- --:--:-- --:--:-- 21475
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg.orig.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3463k  100 3463k    0     0   378k      0  0:00:09  0:00:09 --:--:--  339k
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.debian.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8004  100  8004    0     0  14159      0 --:--:-- --:--:-- --:--:-- 14159
metis_5.1.0.dfsg-4.dsc:
      Good signature found
   validating metis_5.1.0.dfsg.orig.tar.xz
   validating metis_5.1.0.dfsg-4.debian.tar.xz
All files validated successfully.
dpkg-source: info: extracting metis in metis-5.1.0.dfsg
dpkg-source: info: unpacking metis_5.1.0.dfsg.orig.tar.xz
dpkg-source: info: unpacking metis_5.1.0.dfsg-4.debian.tar.xz
dpkg-source: info: applying 01_fix_installation_paths.patch
Traceback (most recent call last):
  File "/usr/local/bin/launchpad-submit", line 99, in <module>
    args.debuild_params
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 209, in submit_dsc
    orig_tarball, debian_dir = _get_items_from_dsc(dsc)
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 460, in _get_items_from_dsc
    tar = tarfile.open(debian)
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

What i do wrong?

**Comment by nschloe** [comment] 2016-06-16 08:47
Can up please update to 0.2.6 and try again?

**Comment by kenny-opennix** [comment] 2016-06-16 09:39
i use version from git. Clone yesterday about 23:00 msk tz

**Comment by nschloe** [comment] 2016-06-16 09:41
Alright. I was asking because I cannot reproduce the behavior. I tried on two different machines and it appears to work as expected. I'm wondering what could be wrong there.

**Comment by kenny-opennix** [comment] 2016-06-23 19:07
I try, but get error again

```
ymedvedev@fr01:~$ launchpad-submit   --dsc "http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.dsc"   --ubuntu-releases trusty wily xenial yakkety    --ppa ymedvedev/backport
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2212  100  2212    0     0   4779      0 --:--:-- --:--:-- --:--:--  4779
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg.orig.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3463k  100 3463k    0     0  3008k      0  0:00:01  0:00:01 --:--:-- 6299k
dget: retrieving http://http.debian.net/debian/pool/main/m/metis/metis_5.1.0.dfsg-4.debian.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8004  100  8004    0     0  22288      0 --:--:-- --:--:-- --:--:-- 22288
metis_5.1.0.dfsg-4.dsc:
      Good signature found
   validating metis_5.1.0.dfsg.orig.tar.xz
   validating metis_5.1.0.dfsg-4.debian.tar.xz
All files validated successfully.
dpkg-source: info: extracting metis in metis-5.1.0.dfsg
dpkg-source: info: unpacking metis_5.1.0.dfsg.orig.tar.xz
dpkg-source: info: unpacking metis_5.1.0.dfsg-4.debian.tar.xz
dpkg-source: info: applying 01_fix_installation_paths.patch
Traceback (most recent call last):
  File "/usr/local/bin/launchpad-submit", line 104, in <module>
    args.debuild_params
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 209, in submit_dsc
    orig_tarball, debian_dir = _get_items_from_dsc(dsc)
  File "/usr/local/lib/python2.7/dist-packages/launchpadtools/submit.py", line 460, in _get_items_from_dsc
    tar = tarfile.open(debian)
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

ymedvedev@fr01:~$ launchpad-submit -v
launchpadtools 0.2.6

**Comment by nschloe** [comment] 2016-06-23 19:16
Tried that on two different machines: No problem.

I also noticed that I'm using Python 3, and it's weird that it seems to fall back to 2.7 for you. After all,

```
$ head `which launchpad-submit`
#!/usr/bin/env python3
[...]
```

**Comment by kenny-opennix** [comment] 2016-06-23 21:36
I install with pip

```
ymedvedev@fr01:~/launchpadtools$ head `which launchpad-submit`
#!/usr/bin/python
'''
Automatically create tarball and submit it to launchpad.
'''
import argparse
import launchpadtools
```

and /usr/bin/python in ubuntu 14.04 not python 3, its python 2
Also launchpadlib dont have python 3 version

```
ymedvedev@fr01:~/launchpadtools$ sudo pip3 install --upgrade launchpadlib 
Downloading/unpacking launchpadlib
  Downloading launchpadlib-1.10.3.tar.gz (57kB): 57kB downloaded
  Running setup.py (path:/tmp/pip_build_root/launchpadlib/setup.py) egg_info for package launchpadlib

Downloading/unpacking httplib2 (from launchpadlib)
  Downloading httplib2-0.9.2.zip (210kB): 210kB downloaded
  Running setup.py (path:/tmp/pip_build_root/httplib2/setup.py) egg_info for package httplib2

Downloading/unpacking keyring (from launchpadlib)
  Downloading keyring-9.1-py2.py3-none-any.whl
Downloading/unpacking lazr.restfulclient>=0.9.19 (from launchpadlib)
  Downloading lazr.restfulclient-0.13.1.tar.gz (55kB): 55kB downloaded
  Running setup.py (path:/tmp/pip_build_root/lazr.restfulclient/setup.py) egg_info for package lazr.restfulclient
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/lazr.restfulclient/setup.py", line 19, in <module>
        import ez_setup
      File "/tmp/pip_build_root/lazr.restfulclient/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/lazr.restfulclient/setup.py", line 19, in <module>

    import ez_setup

  File "/tmp/pip_build_root/lazr.restfulclient/ez_setup.py", line 98

    except pkg_resources.VersionConflict, e:

                                        ^

SyntaxError: invalid syntax
```

What distribution/version you use?

**Comment by nschloe** [comment] 2016-06-24 14:08
I just checked launchpadtools from [here](https://pypi.python.org/pypi/launchpadtools) and found that 0.2.6 has python3 in the header. Not sure why this is not the case on your machine. Perhaps a broken system?

**Comment by nschloe** [comment] 2016-08-29 19:04
Closing for lack of response. Feel free to reopen if you continue to observe the error.

**Comment by JordanP** [comment] 2017-04-20 10:20
I just go the same error. The problem is with launchpadlib which depends on lazr.restfulclient which fails to install on Python3.X because of 

```
(py35) jordan@jordan-XPS-13-9350:/opt/stack/tempest$ pip install simplejson launchpadlib
Collecting simplejson
Collecting launchpadlib
  Using cached launchpadlib-1.10.5.tar.gz
Collecting httplib2 (from launchpadlib)
  Using cached httplib2-0.10.3.tar.gz
Collecting keyring (from launchpadlib)
  Using cached keyring-10.3.2-py2.py3-none-any.whl
Collecting lazr.restfulclient>=0.9.19 (from launchpadlib)
  Using cached lazr.restfulclient-0.13.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gbxiykv_/lazr.restfulclient/setup.py", line 19, in <module>
        import ez_setup
      File "/tmp/pip-build-gbxiykv_/lazr.restfulclient/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gbxiykv_/lazr.restfulclient/
```

**Comment by JordanP** [comment] 2017-04-20 10:21
See: https://bugs.launchpad.net/lazr.restfulclient/+bug/1677948

**Comment by nschloe** [comment] 2017-06-01 10:47
Thanks @JordanP for the comment. That particular bug has been fixed in lazr.restfulclient 0.13.4, but this version never made to pypi; see https://bugs.launchpad.net/lazr.restfulclient/+bug/1552595. Seems that the package is unmaintained. :(

**Closed as completed by nschloe** 2017-06-01 10:47 UTC
